### ISSUE TITLE
Accessibility checklist

### ISSUE THREAD

**Issue by HendX** [CrunchyBagel/TracePrivately#35]
The app needs to be as accessible to as many people as possible, especially when you consider the older population have generally been considered to be the most at-risk.

- [ ] Support dynamic text sizing
- [ ] Ensure VoiceOver works correctly

**Comment by azzoor** [comment]
Not a complete list but a few more features I can think of are:
- [ ] Accessibility Labels, localised, short
- [ ] Accessibility traits, buttons, image, headings
- [ ] Order of UI elements when using VoiceOver
- [ ] Grouping of UI elements, grouping labels and value labels that make sense
- [ ] Supports Switch Control
- [ ] Custom actions to reduce taps when using VoiceOver/Switch Control
- [ ] VoiceControl, check Accessibility label length
- [ ] Colour contrast on buttons and text
